### ISSUE TITLE
Feature Request: OwnYourSwarm posts should trigger weather lookup

### ISSUE THREAD

**Issue by chrisaldrich** [dshanske/simple-location#75] opened 2018-08-01 17:13 UTC
Currently OwnYourSwarm will allow crossposts with GPS data that allows Simple Location to display. Though OYS doesn't send the weather data, I presume it could be possible that upon receipt of the OYS data that Simple Location could still be triggered to do a weather lookup so that the checkin could display both the location as well as the weather data for that checkin.

Taking things a half step further, perhaps any micropub or other incoming post creation tool that includes location data could automatically trigger a weather lookup? Then OwnYourGram, DsgnWrks Instagram Importer, or other similar tools that create new posts with location data could provide weather as well.

(Originally posted at https://boffosocko.com/2018/08/01/feature-request-ownyourswarm-posts-should-trigger-weather-lookup/)

**Comment by dshanske** [comment] 2018-10-16 04:47
Duplicate of #51

**Closed** 2018-10-16 04:47 UTC
